import { useEffect, useRef } from 'react'
import { io } from 'socket.io-client'
import useStore from '../store/useStore'

const SOCKET_URL = import.meta.env.VITE_SOCKET_URL || 'http://localhost:3000'

/**
 * Establishes the Socket.IO connection and wires incoming events to
 * the Zustand store. Should be called ONCE at the root of the app.
 *
 * @returns {React.MutableRefObject<import('socket.io-client').Socket|null>}
 */
export function useSocket() {
  const socketRef = useRef(null)
  const { setConnected, setDevices, updateDevice, pushTempReading, addEvent, upsertPrediction, upsertAlert, updateAlertState, prependLifecycleEvent } = useStore()

  useEffect(() => {
    const socket = io(SOCKET_URL, {
      transports: ['websocket', 'polling'],
      reconnectionAttempts: 10,
      reconnectionDelay: 2000,
    })

    socketRef.current = socket

    socket.on('connect', () => {
      console.info('[Socket] Connected:', socket.id)
      setConnected(true)
    })

    socket.on('disconnect', (reason) => {
      console.warn('[Socket] Disconnected:', reason)
      setConnected(false)
    })

    socket.on('connect_error', (err) => {
      console.error('[Socket] Connection error:', err.message)
    })

    // Initial snapshot sent by server on every new connection
    socket.on('devices:snapshot', (devices) => {
      setDevices(devices)
      devices.forEach((d) => pushTempReading(d.deviceId, d.temperature))
    })

    // Per-device real-time update (after network simulation pass-through)
    socket.on('device:update', (device) => {
      updateDevice(device)
      pushTempReading(device.deviceId, device.temperature)
    })

    // Anomaly events generated by backend
    socket.on('anomaly:detected', (event) => {
      addEvent(event)
    })

    // Predictive failure updates from backend PredictionService
    socket.on('prediction:update', (payload) => {
      upsertPrediction(payload)
    })

    // Alert lifecycle events from backend AlertService
    socket.on('alert:update', ({ action, alert }) => {
      if (action === 'triggered') {
        upsertAlert(alert)
      } else if (action === 'resolved') {
        updateAlertState(alert.alertId, { state: 'resolved', resolvedAt: alert.resolvedAt })
      }
    })

    // Device lifecycle state changes
    socket.on('lifecycle:change', (event) => {
      prependLifecycleEvent(event)
    })

    return () => {
      socket.disconnect()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  return socketRef
}
